### ISSUE TITLE
Invalid HTML on card

### ISSUE THREAD

**Issue by Superkick2sweet** [luisscholl/japanese-card-templates-for-anki#3]
Error message when trying to preview/study any card made using this template (including the example cards):

**"Invalid HTML on card: TypeError: Cannot read property '__k' of undefined"**

Error only appears on desktop Anki (I'm using Anki ver 2.1.15 on MacOS Catalina ver 10.15.3). Seems fine on iOS Anki app.

**Comment by luisscholl** [comment]
Thanks for catching this!
I can reproduce it and will look into whether I can fix it, when I have the time.

**Comment by luisscholl** [comment]
Hi,
I just rebuilt the card templates and uploaded them. Weirdly it is now working for me on Anki Desktop again without any modifications to the code. (First card is still buggy, just click on "Show Answer" to see the special first back side, which is both the front and the back.)

Could you test whether this fixes it for you, please?

Preview just does not work and I do not see a way to fix it as it seems to behave like the first card. With Anki's undocumented JavaScript, it is very hard to reliably load JavaScript and I am happy that the framework gets loaded at all.

**Comment by Superkick2sweet** [comment]
Hi, no problem and thanks for looking into it. I just downloaded the latest version from AnkiWeb, but still getting the same error when previewing the card or in reviews.

I have also just noticed that when I switch the other side of the card in preview mode, I get s different error: "Invalid HTML on card: TypeError: window.Persistence.getItem is not a function"

**Comment by luisscholl** [comment]
Hm, I cannot reproduce that unfortunately. Could you try upgrading Anki to the latest stable version (2.1.23)? Anki changed the way it combines card templates and fields in 2.1.20 .
